apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ankitjhunjhunwala03/order-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_NAME
              value: order_db
            - name: DB_USER
              value: order_user
            - name: DB_PASSWORD
              value: order_pass
            - name: DB_HOST
              value: db-order
            - name: DB_PORT
              value: "5432"
            - name: AUTH_SERVICE_URL
              value: "http://localhost:8000"
            - name: PRODUCT_SERVICE_URL
              value: "http://localhost:8001"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
